### ISSUE TITLE
Crash when fighting Invisible Men in vcmi 1.6

### ISSUE THREAD

**Issue by Warzyw647** [vcmi-mods/invisible-man#5]
Game crashes when entering a battle against neutral Invisible Men, in and out of creature bank.
Game crashes after a hero who has some Invisible Men in army starts a battle and tries to attack with them.
Crashes don't seem related to the creature bank format update as they also happen against neutral Invisible Men when there are no creature banks present on the map.
Happens on develop version of vcmi.

Apparently something wrong with Invisible Men animations in the new vcmi version. The creatures worked fine in vcmi 1.5.7.

Not sure if this is a problem to be solved here or in vcmi code.

**Comment by misiokles** [comment]
Fixed

**Comment by Warzyw647** [comment]
Now crashes less for me on beta branch.
Only when the Invisibles are supposed to face left.
Either when they start the battle as defenders or when they're in my army and I order them to go back.
